### ISSUE TITLE
Procurement handbook feedback

### ISSUE THREAD

**Issue by andrewmaier** [codeforamerica/codeforamerica.org#1249]
cc @danhon 

Saw this by way of Michelle Hertzfeldt at 18F! What a wonderful idea. This is something that I think governments should be thinking about and I 👏 Code for America for prompting the conversation. 

Feedback in no specific order:

First: CfA setting their headlines/titles in Interstate is pretty great! Otherwise the (graphic) design of this playbook feels generic.

Second: In the interest of plain language: when you say: "ALPHA: The information on this page is in alpha, which means..." Something isn't plain language if you have to explain what it means, right? Wouldn't it be easier to just say “This page is being drafted. We’ll update it as we learn"?

Third: The Wardley map is kind of confusing but slightly enlightening? There's really no other way to say this: I'm not sure if I actually get what it's after, but it is interesting to think of a larger project in terms of sub projects that mature at different paces!

Fourth: The "Delivering digital services” section really really feels like a recap of the [USDS playbook](https://playbook.cio.gov/) and [GDS’s Design principles](https://www.gov.uk/design-principles). I'd encourage you to just link to those from the intro page as pre-requisites/assumed knowledge.

That's all from me for now. As I said, this is a really great idea :)
-Andrew

**Comment by danhon** [comment]
Hey Andrew - thanks for the feedback. The layout and graphic design is just a tweak of the minimal code documentation layout already in use by CfA and is more about readability than identity right now. The whole idea of just-get-the-documentation-out-there-and-correct first, rather than spending time on the identity. 

I agree with the Alpha language, so I've updated it. 

I'll have a think about the Wardley map and making it clearer. And whilst "delivering digital services" is in some cases a recap of the USDS playbook, I think it's still useful for us to recap them in a more specific manner to the problem at hand, rather than just tell our users to go somewhere else.
