### ISSUE TITLE
use HTTPS

### ISSUE THREAD

**Issue by jden** [codeforamerica/codeforamerica.org#529]
- 18F has an HTTP-by-default policy: https://github.com/18F/api-standards#always-use-https
- Google has announced that they will be factoring HTTPS into their ranking facotrs http://googleonlinesecurity.blogspot.com/2014/08/https-as-ranking-signal_6.html
- See also this presentation on HTTPS Everywhere from Google/IO https://docs.google.com/presentation/d/15H8Sj-Zol1tcum0CSylhmXns5r7cvNFtzYrcwAzkTjM/present#slide=id.g12f3ee71d_10 (video: https://www.youtube.com/watch?v=cBhZ6S0PFCY)

The entire codeforamerica.org site - including and especially /api - should be served exclusively over HTTPS

**Comment by rebeccawilliams** [comment]
@migurski, any way we can reopen this issue? 

I tried to embed the *fantastic* [civic issue finder](http://www.codeforamerica.org/geeks/civicissues/embed) today, but can't use it because of mixed content issues: 

![screen shot 2015-02-02 at 2 49 09 pm](https://cloud.githubusercontent.com/assets/1725454/6008039/82cdab68-aaec-11e4-8794-cd2fcebca42b.png)

**Comment by adelevie** [comment]
:+1:, @rebeccawilliams.

 Since @konklone wrote [this](https://github.com/codeforamerica/codeforamerica.org/issues/529#issuecomment-52212122), SSL with nginx has become even easier thanks to @vzvenyach's [nginx-ssl script](https://github.com/vzvenyach/nginx-ssl). As long as someone in your organization can open email from any of the following accounts, setting up SSL with nginx will *literally* take less than 15 minutes:

- The webmaster@, hostmaster@, postmaster@, admin@, or administrator@ addresses at either your domain or the sub-domain for which you are buying a certificate.
- One of the email addresses listed in the publicly-available whois record for your domain. (Note: this is only available with TLDs that publish email addresses in the public whois system.)

(from the [sslmate faq](https://sslmate.com/faq))

**Comment by konklone** [comment]
Code For America's servers use Apache, but the issue is fundamentally the same - make the .crt and .key using SSLMate, and then point Apache at them.

[CourtListener](https://www.courtlistener.com/) is an example of a civic tech app that uses HTTPS on Apache, and they use [this configuration](https://github.com/freelawproject/courtlistener/blob/master/apache/courtlistener.com.conf#L80-L91) to get [an A SSL Labs grade](https://www.ssllabs.com/ssltest/analyze.html?d=courtlistener.com). The only reason they don't get an A+ is because of the SHA-1 certificate -- and you won't run into that with SSLMate, which uses SHA-2.

**Comment by migurski** [comment]
We’ve been slowly getting up on SSL, starting with upstream dependencies like https://style.codeforamerica.org. I’ve left https://www.codeforamerica.org as the final domain to get an updates.

**Comment by migurski** [comment]
SSL is up on the main domain: https://www.codeforamerica.org/

I may need some help testing to make sure that it’s embeddable, @ondrae or @rebeccawilliams.

**Comment by rebeccawilliams** [comment]
Awesome! Awesome! I'll test today and let you know.

**Comment by rebeccawilliams** [comment]
Looks like there are still issues, see: https://codeforamerica.org/geeks/civicissues/widget?organization_name=Data.gov&labels=help%20wanted&number=12, @ondrae?

**Comment by migurski** [comment]
Looks okay with the `www.` added: https://www.codeforamerica.org/geeks/civicissues/widget?organization_name=Data.gov&labels=help%2520wanted&number=12

**Comment by rebeccawilliams** [comment]
Ah! The embed styling is off though: 
![screen shot 2015-02-04 at 1 30 29 pm](https://cloud.githubusercontent.com/assets/1725454/6046624/e979e792-ac71-11e4-9342-ce60f6bb7cda.png)

I think the embed tool links need to be updated to https:// to fix.

**Comment by jden** [comment]
:clap: :clap: :clap: :tada: :confetti_ball: :beers:

**Comment by konklone** [comment]
There are links to insrecure `http://` images and stylesheets. Fortunately, `style.codeforamerica.org` has `https://` enabled, so some updates to the links should fix it.

**Comment by ondrae** [comment]
I'm working on the https links in the civic issue finder.

**Comment by ondrae** [comment]
Got it. Try it out now.

**Comment by rebeccawilliams** [comment]
Embed works and is live: https://www.data.gov/developers/open-source

Thank you **so much**. In the words of @jden: :clap::clap::clap::tada::confetti_ball::beers:

**Comment by migurski** [comment]
Yeah! :cocktail: :ok_hand:

**Comment by jden** [comment]
Following up on this:

- is there any intention of redirecting http -> https? Ideally, this would be in place with [HSTS](https://www.owasp.org/index.php/HTTP_Strict_Transport_Security) headers enabled. 
- There are still insecure resources on the page:
![image](https://cloud.githubusercontent.com/assets/1106489/7095444/61f48606-df7f-11e4-84ea-084f7ebccb7e.png)

In transitioning to HTTPS-only resources, you can use Content Security Policy reporting to figure out which resources are being loaded without TLS by setting policy in `Report-Only` mode to only allow https and setting a report endpoint, eg `Content-Security-Policy-Report-Only: default-src https:; report-uri: https://codeforamerica.org/csp-report-endpoint`. See http://content-security-policy.com/ for more

**Comment by jden** [comment]
From dev tools: 
![image](https://cloud.githubusercontent.com/assets/1106489/7095565/5b9c4392-df80-11e4-915e-4f837d26c9ff.png)

**Comment by konklone** [comment]
It looks like @jden has made some great progress in #1021 and #1022.

@jden, take a look at https://github.com/codeforamerica/codeforamerica.org/pull/912 -- I did a lot of this work there a couple months back, but it was unmerged and now has a conflict and needs to get re-synced with `master`. Feel free to either resolve the conflict, or borrow it for inspiration.
