### ISSUE TITLE
Links on README link to alpha site and are broken

### ISSUE THREAD

**Issue by maya** [codeforamerica/codeforamerica.org#842]
All the links under the "Specific help we need"

**Comment by davidrleonard** [comment]
Thanks @maya.

* Reference 78a4334 to see @maya's past updates to the README to fix old alpha.codeforamerica.org links
* I'm pretty sure those instructions didn't generate a PR for you because you have permissions to commit to master, so it just did that
* Fix to section referencing "big list of people" coming
