### ISSUE TITLE
Organize the staff page

### ISSUE THREAD

**Issue by davidrleonard** [codeforamerica/codeforamerica.org#915]
Find a way to organize our staff (and maybe 2015 fellow list?) page to make it easier to see who is on what team.

//cc @Jaime-Alexis @alanjosephwilliams @RebeccaCoelius

**Comment by evanwolf** [comment]
bonus points for... 
- people search (the number of people is large, getting larger)  
- contact forms for each person (send an email or a text message)
- include board members 
- include staff, board, fellow alumni in search
- adding brigade captains

**Comment by migurski** [comment]
@phae did this last year: https://jekit.codeforamerica.org/codeforamerica/codeforamerica.org/team-reorg/about/team/

It’s out of date, but contains the general idea.

**Comment by Jaime-Alexis** [comment]
Awesome, let's get something like @phae's thing going. 

I like some of @evanwolf's ideas but @davidrleonard would want to test/talk about contact. One thing it made me realize is that it's probably why Jen gets pinged on LinkedIn for speaking requests...because people see her LI profile. Maybe incorporating some form of contact, but not in a way that floods someone's phone or inbox (which might happen particularly to Board members and Jen).

**Comment by phae** [comment]
I think a good MVP would be to simply rearrange the page akin to how I had
done it last year (by teams, making it clearer who does what) then have an
obvious contact link somewhere to the general "contact us" and/or "request
a speaker" and see how that goes for a while in terms of traffic. :)

**Comment by Jaime-Alexis** [comment]
+1

--------------------------------------------------------------------------------------------------------------------------------
Jaime-Alexis Fowler | Director of Marketing | *Code for America*
<http://codeforamerica.org/> | p:*214.673.9060* | @JaimeAlexis
<http://www.twitter.com/JaimeAlexis>

*Bring the Code for America Fellowship to your city in 2016. Learn how.
<http://www.codeforamerica.org/governments/fellowship/>*

**Comment by davidrleonard** [comment]
It's been reorganized a few times. @evanwolf's feature ideas are great, maybe for a future iteration.
